<?xml version="1.0" encoding="UTF-8" ?>
<testsuites name="vitest tests" tests="1" failures="1" errors="0" time="0">
    <testsuite name="tests/api/auth-verify.test.ts" timestamp="2025-09-06T12:01:42.249Z" hostname="c82ba9db4d53" tests="1" failures="1" errors="0" skipped="0" time="0">
        <testcase classname="tests/api/auth-verify.test.ts" name="tests/api/auth-verify.test.ts" time="0">
            <failure message="[vitest] There was an error when mocking a module. If you are using &quot;vi.mock&quot; factory, make sure there are no top level variables inside, since this call is hoisted to top of the file. Read more: https://vitest.dev/api/vi.html#vi-mock" type="Error">
Error: [vitest] There was an error when mocking a module. If you are using &quot;vi.mock&quot; factory, make sure there are no top level variables inside, since this call is hoisted to top of the file. Read more: https://vitest.dev/api/vi.html#vi-mock
 ❯ apps/web/pages/api/auth/verify.ts:1:1

Caused by: Caused by: ReferenceError: Cannot access &apos;mockGenerateError&apos; before initialization
 ❯ tests/api/auth-verify.test.ts:42:18
 ❯ apps/web/pages/api/auth/verify.ts:1:1
            </failure>
        </testcase>
    </testsuite>
</testsuites>
